# Generated by Django 3.2.5 on 2021-07-20 02:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_rename_portfoilo_port'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Port',
            new_name='Post',
        ),
    ]
