# Generated by Django 3.2.5 on 2021-07-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_port_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post/%Y/%m/%d'),
        ),
    ]
